[phases.setup]
nixPkgs = ['curl', 'ffmpeg', 'python3', 'python3Packages.pip']

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install yt-dlp",
  "python3 -m pip install --upgrade yt-dlp"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node server.js" 
