[phases.setup]
nixPkgs = ['curl', 'ffmpeg', 'python3', 'python3Packages.pip']

[phases.install]
cmds = [
  "pip install --upgrade pip",
  'pip3 install --user yt-dlp'
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node server.js" 
